#!/bin/bash
# 从 build_dir/system/fonts/ 生成 manifest.txt
# 用法: scripts/gen_manifest.sh <fonts_dir> > manifest.txt

FONTS_DIR="${1:-build_dir/system/fonts}"

echo "# GoogleSansMax Font Manifest"
echo "# Auto-generated by CI. Do not edit manually."
echo "# Format: filename|sha256|filesize"
echo "#"

for f in "$FONTS_DIR"/*; do
    [ -f "$f" ] || continue
    NAME=$(basename "$f")
    HASH=$(sha256sum "$f" | cut -d' ' -f1)
    SIZE=$(wc -c < "$f")
    echo "$NAME|$HASH|$SIZE"
done
